### DISCUSSION TITLE
aMQTT plugin configuration

### DISCUSSION THREAD

**Discussion by ajmirsky** [Yakifo/amqtt#179] [Polls]
currently, the broker configuration is very forgiving when it comes to initializing plugins
```
listeners:
  default:
    bind: 127.0.0.1:1884
    type: tcp
```

even without specifying any auth (anonymous, password), amqtt loads both plugins.

if you specify the auth anonymous feature, it assumes you want the associated plugin loaded:

```
auth:
  allow-anonymous: true
listeners:
  default:
    bind: 127.0.0.1:1884
    type: tcp
```

also, if you specify a sys_interval other than zero, it will assume you want to load the $SYS plugin loaded:

```
listeners:
  default:
    bind: 127.0.0.1:1884
    type: tcp
sys_interval: 10
```

It makes a user not have to worry about what plugins are, so 'no fuss', although, you could be inadvertently loading/configuring some functionality without knowing it. Should we be more explicit with configs, requiring plugins that are depended on declared?
